// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCurrentRound, getResults, type Options, startMatch, submitGuess } from '../sdk.gen';
import type {
  GetCurrentRoundData,
  GetCurrentRoundError,
  GetCurrentRoundResponse,
  GetResultsData,
  GetResultsError,
  GetResultsResponse,
  StartMatchData,
  SubmitGuessData,
} from '../types.gen';

/**
 * Start a match
 */
export const startMatchMutation = (
  options?: Partial<Options<StartMatchData>>
): UseMutationOptions<unknown, DefaultError, Options<StartMatchData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<StartMatchData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await startMatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Submit a guess
 */
export const submitGuessMutation = (
  options?: Partial<Options<SubmitGuessData>>
): UseMutationOptions<unknown, DefaultError, Options<SubmitGuessData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SubmitGuessData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await submitGuess({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getCurrentRoundQueryKey = (options: Options<GetCurrentRoundData>) =>
  createQueryKey('getCurrentRound', options);

/**
 * Get current round
 */
export const getCurrentRoundOptions = (options: Options<GetCurrentRoundData>) =>
  queryOptions<
    GetCurrentRoundResponse,
    GetCurrentRoundError,
    GetCurrentRoundResponse,
    ReturnType<typeof getCurrentRoundQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentRound({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrentRoundQueryKey(options),
  });

export const getResultsQueryKey = (options: Options<GetResultsData>) =>
  createQueryKey('getResults', options);

/**
 * Get match results
 */
export const getResultsOptions = (options: Options<GetResultsData>) =>
  queryOptions<
    GetResultsResponse,
    GetResultsError,
    GetResultsResponse,
    ReturnType<typeof getResultsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getResults({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getResultsQueryKey(options),
  });
