// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  CreateRoomData,
  CreateRoomResponses,
  GetRoomData,
  GetRoomErrors,
  GetRoomResponses,
  JoinRoomData,
  JoinRoomErrors,
  JoinRoomResponses,
  LeaveRoomData,
  LeaveRoomErrors,
  LeaveRoomResponses,
  ListOpenRoomsData,
  ListOpenRoomsResponses,
  UpdateSettingsData,
  UpdateSettingsErrors,
  UpdateSettingsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List open rooms
 *
 * Returns all rooms with OPEN status.
 */
export const listOpenRooms = <ThrowOnError extends boolean = false>(
  options?: Options<ListOpenRoomsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListOpenRoomsResponses, unknown, ThrowOnError>({
    url: '/api/v1/rooms',
    ...options,
  });

/**
 * Create a room
 *
 * Creates a new room and publishes a game.room.events Kafka event.
 */
export const createRoom = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoomData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateRoomResponses, unknown, ThrowOnError>({
    url: '/api/v1/rooms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Join a room
 *
 * Adds a player to the lobby.
 */
export const joinRoom = <ThrowOnError extends boolean = false>(
  options: Options<JoinRoomData, ThrowOnError>
) =>
  (options.client ?? client).post<JoinRoomResponses, JoinRoomErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/join',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update room settings
 *
 * Updates round count, time limit, or game pack. Host-only.
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSettingsData, ThrowOnError>
) =>
  (options.client ?? client).patch<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get room details
 *
 * Returns room details including players, settings, and status.
 */
export const getRoom = <ThrowOnError extends boolean = false>(
  options: Options<GetRoomData, ThrowOnError>
) =>
  (options.client ?? client).get<GetRoomResponses, GetRoomErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}',
    ...options,
  });

/**
 * Leave a room
 *
 * Removes yourself from the lobby. If the host leaves, the room is closed.
 */
export const leaveRoom = <ThrowOnError extends boolean = false>(
  options: Options<LeaveRoomData, ThrowOnError>
) =>
  (options.client ?? client).delete<LeaveRoomResponses, LeaveRoomErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/leave',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
