// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8083' | (string & {});
};

/**
 * Request to create a new room
 */
export type CreateRoomRequest = {
  /**
   * ID of the host player creating the room
   */
  hostId: string;
  /**
   * Whether the room is private (invite-only)
   */
  isPrivate?: boolean;
};

/**
 * A player in the room
 */
export type PlayerResponse = {
  /**
   * Player's user ID
   */
  playerId?: string;
  /**
   * Player's display name
   */
  displayName?: string;
  /**
   * Timestamp when the player joined
   */
  joinedAt?: string;
};

/**
 * Room details including players and settings
 */
export type RoomResponse = {
  /**
   * Unique 6-character room code
   */
  roomCode?: string;
  /**
   * User ID of the room host
   */
  hostId?: string;
  /**
   * Current room status
   */
  status?: 'OPEN' | 'IN_PROGRESS' | 'FINISHED' | 'CLOSED';
  /**
   * Maximum number of players allowed
   */
  maxPlayers?: number;
  /**
   * Room game settings
   */
  settings?: SettingsResponse;
  /**
   * List of players currently in the room
   */
  players?: Array<PlayerResponse>;
  /**
   * Timestamp when the room was created
   */
  createdAt?: string;
  private?: boolean;
};

/**
 * Game settings for the room
 */
export type SettingsResponse = {
  /**
   * Number of rounds per match
   */
  roundCount?: number;
  /**
   * Time limit per round in seconds
   */
  timeLimitSeconds?: number;
  /**
   * Game pack identifier
   */
  gamePack?: string;
};

/**
 * Request to join a room
 */
export type JoinRoomRequest = {
  /**
   * ID of the player joining
   */
  playerId: string;
  /**
   * Display name of the player
   */
  displayName: string;
};

/**
 * Request to update room settings (host-only)
 */
export type UpdateSettingsRequest = {
  /**
   * ID of the player requesting changes (must be host)
   */
  playerId: string;
  /**
   * Number of rounds per match
   */
  roundCount?: number;
  /**
   * Time limit per round in seconds
   */
  timeLimitSeconds?: number;
  /**
   * Game pack identifier
   */
  gamePack?: string;
};

/**
 * Request to leave a room
 */
export type LeaveRoomRequest = {
  /**
   * ID of the player leaving
   */
  playerId: string;
};

export type ListOpenRoomsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/rooms';
};

export type ListOpenRoomsResponses = {
  /**
   * Room list returned
   */
  200: Array<RoomResponse>;
};

export type ListOpenRoomsResponse = ListOpenRoomsResponses[keyof ListOpenRoomsResponses];

export type CreateRoomData = {
  body: CreateRoomRequest;
  path?: never;
  query?: never;
  url: '/api/v1/rooms';
};

export type CreateRoomResponses = {
  /**
   * Room created
   */
  201: RoomResponse;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type JoinRoomData = {
  body: JoinRoomRequest;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/join';
};

export type JoinRoomErrors = {
  /**
   * Room not found
   */
  404: RoomResponse;
  /**
   * Room full or player already in room
   */
  409: RoomResponse;
};

export type JoinRoomError = JoinRoomErrors[keyof JoinRoomErrors];

export type JoinRoomResponses = {
  /**
   * Player joined
   */
  200: RoomResponse;
};

export type JoinRoomResponse = JoinRoomResponses[keyof JoinRoomResponses];

export type UpdateSettingsData = {
  body: UpdateSettingsRequest;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/settings';
};

export type UpdateSettingsErrors = {
  /**
   * Not the host
   */
  403: RoomResponse;
  /**
   * Room not found
   */
  404: RoomResponse;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
  /**
   * Settings updated
   */
  200: RoomResponse;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type GetRoomData = {
  body?: never;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}';
};

export type GetRoomErrors = {
  /**
   * Room not found
   */
  404: RoomResponse;
};

export type GetRoomError = GetRoomErrors[keyof GetRoomErrors];

export type GetRoomResponses = {
  /**
   * Room details returned
   */
  200: RoomResponse;
};

export type GetRoomResponse = GetRoomResponses[keyof GetRoomResponses];

export type LeaveRoomData = {
  body: LeaveRoomRequest;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/leave';
};

export type LeaveRoomErrors = {
  /**
   * Room not found
   */
  404: unknown;
};

export type LeaveRoomResponses = {
  /**
   * Player left
   */
  204: void;
};

export type LeaveRoomResponse = LeaveRoomResponses[keyof LeaveRoomResponses];
