// This file is auto-generated by @hey-api/openapi-ts

export { getMatchScores, getRoundScores, type Options } from './sdk.gen';
export type {
  ClientOptions,
  GetMatchScoresData,
  GetMatchScoresResponse,
  GetMatchScoresResponses,
  GetRoundScoresData,
  GetRoundScoresResponse,
  GetRoundScoresResponses,
  ScoreItem,
  ScoresResponse,
} from './types.gen';
