// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetMatchScoresData,
  GetMatchScoresResponses,
  GetRoundScoresData,
  GetRoundScoresResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get match scores
 *
 * Returns all scores for an entire match.
 */
export const getMatchScores = <ThrowOnError extends boolean = false>(
  options: Options<GetMatchScoresData, ThrowOnError>
) =>
  (options.client ?? client).get<GetMatchScoresResponses, unknown, ThrowOnError>({
    url: '/api/v1/scoring/{roomCode}',
    ...options,
  });

/**
 * Get round scores
 *
 * Returns all scores for a specific round.
 */
export const getRoundScores = <ThrowOnError extends boolean = false>(
  options: Options<GetRoundScoresData, ThrowOnError>
) =>
  (options.client ?? client).get<GetRoundScoresResponses, unknown, ThrowOnError>({
    url: '/api/v1/scoring/{roomCode}/rounds/{roundNumber}',
    ...options,
  });
