// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8084' | (string & {});
};

/**
 * A single score record for one player and one phase
 */
export type ScoreItem = {
  /**
   * Unique score record ID
   */
  id?: string;
  /**
   * Round number (1-based)
   */
  roundNumber?: number;
  /**
   * Player's user ID
   */
  playerId?: string;
  /**
   * Phase this score belongs to
   */
  phase?: 'GAME' | 'LEVEL' | 'SPOT';
  /**
   * Points earned for this phase
   */
  points?: number;
  /**
   * Whether the answer was correct
   */
  correct?: boolean;
  /**
   * Time bonus applied in milliseconds (LEVEL phase only)
   */
  timeBonusMs?: number;
  /**
   * Timestamp when the score was recorded
   */
  createdAt?: string;
};

/**
 * Scores for a room, optionally filtered by round
 */
export type ScoresResponse = {
  /**
   * Room code the scores belong to
   */
  roomCode?: string;
  /**
   * List of individual score records
   */
  scores?: Array<ScoreItem>;
};

export type GetMatchScoresData = {
  body?: never;
  path: {
    /**
     * Room code
     */
    roomCode: string;
  };
  query?: never;
  url: '/api/v1/scoring/{roomCode}';
};

export type GetMatchScoresResponses = {
  /**
   * Scores returned
   */
  200: ScoresResponse;
};

export type GetMatchScoresResponse = GetMatchScoresResponses[keyof GetMatchScoresResponses];

export type GetRoundScoresData = {
  body?: never;
  path: {
    /**
     * Room code
     */
    roomCode: string;
    /**
     * Round number
     */
    roundNumber: number;
  };
  query?: never;
  url: '/api/v1/scoring/{roomCode}/rounds/{roundNumber}';
};

export type GetRoundScoresResponses = {
  /**
   * Scores returned
   */
  200: ScoresResponse;
};

export type GetRoundScoresResponse = GetRoundScoresResponses[keyof GetRoundScoresResponses];
