// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  createRoom,
  getRoom,
  joinRoom,
  leaveRoom,
  listOpenRooms,
  type Options,
  updateSettings,
} from '../sdk.gen';
import type {
  CreateRoomData,
  CreateRoomResponse,
  GetRoomData,
  GetRoomError,
  GetRoomResponse,
  JoinRoomData,
  JoinRoomError,
  JoinRoomResponse,
  LeaveRoomData,
  LeaveRoomResponse,
  ListOpenRoomsData,
  ListOpenRoomsResponse,
  UpdateSettingsData,
  UpdateSettingsError,
  UpdateSettingsResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listOpenRoomsQueryKey = (options?: Options<ListOpenRoomsData>) =>
  createQueryKey('listOpenRooms', options);

/**
 * List open rooms
 *
 * Returns all rooms with OPEN status.
 */
export const listOpenRoomsOptions = (options?: Options<ListOpenRoomsData>) =>
  queryOptions<
    ListOpenRoomsResponse,
    DefaultError,
    ListOpenRoomsResponse,
    ReturnType<typeof listOpenRoomsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listOpenRooms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listOpenRoomsQueryKey(options),
  });

/**
 * Create a room
 *
 * Creates a new room and publishes a game.room.events Kafka event.
 */
export const createRoomMutation = (
  options?: Partial<Options<CreateRoomData>>
): UseMutationOptions<CreateRoomResponse, DefaultError, Options<CreateRoomData>> => {
  const mutationOptions: UseMutationOptions<
    CreateRoomResponse,
    DefaultError,
    Options<CreateRoomData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRoom({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Join a room
 *
 * Adds a player to the lobby.
 */
export const joinRoomMutation = (
  options?: Partial<Options<JoinRoomData>>
): UseMutationOptions<JoinRoomResponse, JoinRoomError, Options<JoinRoomData>> => {
  const mutationOptions: UseMutationOptions<
    JoinRoomResponse,
    JoinRoomError,
    Options<JoinRoomData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await joinRoom({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update room settings
 *
 * Updates round count, time limit, or game pack. Host-only.
 */
export const updateSettingsMutation = (
  options?: Partial<Options<UpdateSettingsData>>
): UseMutationOptions<UpdateSettingsResponse, UpdateSettingsError, Options<UpdateSettingsData>> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingsResponse,
    UpdateSettingsError,
    Options<UpdateSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRoomQueryKey = (options: Options<GetRoomData>) =>
  createQueryKey('getRoom', options);

/**
 * Get room details
 *
 * Returns room details including players, settings, and status.
 */
export const getRoomOptions = (options: Options<GetRoomData>) =>
  queryOptions<GetRoomResponse, GetRoomError, GetRoomResponse, ReturnType<typeof getRoomQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoom({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRoomQueryKey(options),
  });

/**
 * Leave a room
 *
 * Removes yourself from the lobby. If the host leaves, the room is closed.
 */
export const leaveRoomMutation = (
  options?: Partial<Options<LeaveRoomData>>
): UseMutationOptions<LeaveRoomResponse, DefaultError, Options<LeaveRoomData>> => {
  const mutationOptions: UseMutationOptions<
    LeaveRoomResponse,
    DefaultError,
    Options<LeaveRoomData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await leaveRoom({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
