// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getMatchScores, getRoundScores, type Options } from '../sdk.gen';
import type {
  GetMatchScoresData,
  GetMatchScoresResponse,
  GetRoundScoresData,
  GetRoundScoresResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getMatchScoresQueryKey = (options: Options<GetMatchScoresData>) =>
  createQueryKey('getMatchScores', options);

/**
 * Get match scores
 *
 * Returns all scores for an entire match.
 */
export const getMatchScoresOptions = (options: Options<GetMatchScoresData>) =>
  queryOptions<
    GetMatchScoresResponse,
    DefaultError,
    GetMatchScoresResponse,
    ReturnType<typeof getMatchScoresQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMatchScores({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMatchScoresQueryKey(options),
  });

export const getRoundScoresQueryKey = (options: Options<GetRoundScoresData>) =>
  createQueryKey('getRoundScores', options);

/**
 * Get round scores
 *
 * Returns all scores for a specific round.
 */
export const getRoundScoresOptions = (options: Options<GetRoundScoresData>) =>
  queryOptions<
    GetRoundScoresResponse,
    DefaultError,
    GetRoundScoresResponse,
    ReturnType<typeof getRoundScoresQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoundScores({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRoundScoresQueryKey(options),
  });
