// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getGlobalLeaderboard, getRoomLeaderboard, type Options } from '../sdk.gen';
import type {
  GetGlobalLeaderboardData,
  GetGlobalLeaderboardResponse,
  GetRoomLeaderboardData,
  GetRoomLeaderboardResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getRoomLeaderboardQueryKey = (options: Options<GetRoomLeaderboardData>) =>
  createQueryKey('getRoomLeaderboard', options);

/**
 * Get room leaderboard
 *
 * Returns the current ranking within a specific room.
 */
export const getRoomLeaderboardOptions = (options: Options<GetRoomLeaderboardData>) =>
  queryOptions<
    GetRoomLeaderboardResponse,
    DefaultError,
    GetRoomLeaderboardResponse,
    ReturnType<typeof getRoomLeaderboardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoomLeaderboard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRoomLeaderboardQueryKey(options),
  });

export const getGlobalLeaderboardQueryKey = (options?: Options<GetGlobalLeaderboardData>) =>
  createQueryKey('getGlobalLeaderboard', options);

/**
 * Get global leaderboard
 *
 * Returns top players across all games.
 */
export const getGlobalLeaderboardOptions = (options?: Options<GetGlobalLeaderboardData>) =>
  queryOptions<
    GetGlobalLeaderboardResponse,
    DefaultError,
    GetGlobalLeaderboardResponse,
    ReturnType<typeof getGlobalLeaderboardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGlobalLeaderboard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGlobalLeaderboardQueryKey(options),
  });
