/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/rooms/{code}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start a match
     * @description Transitions the room state to IN_PROGRESS and generates 5 rounds with placeholder coordinates.
     */
    post: operations['startMatch'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rooms/{code}/guess': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a guess
     * @description Accepts the player's guess for the current phase and publishes a player.guess.submitted event to Kafka.
     */
    post: operations['submitGuess'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rooms/{code}/round': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current round
     * @description Returns the active round's game/level info. True spawn coordinates are NOT included.
     */
    get: operations['getCurrentRound'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rooms/{code}/results': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get match results
     * @description Returns all 5 round results after the match finishes, including true spawn coordinates.
     */
    get: operations['getResults'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Request to start a match for a given room */
    StartMatchRequest: {
      /**
       * @description ID of the host player initiating the match
       * @example user-uuid-123
       */
      hostId: string;
    };
    /** @description A player's guess for the current round phase */
    GuessRequest: {
      /**
       * @description Player's user ID
       * @example user-uuid-456
       */
      playerId: string;
      /**
       * @description Which phase this guess targets
       * @example GAME
       * @enum {string}
       */
      phase: 'GAME' | 'LEVEL' | 'SPOT';
      /**
       * @description Text answer for GAME or LEVEL phase
       * @example Mario Kart 8
       */
      textAnswer?: string;
      /**
       * Format: double
       * @description Guessed X coordinate (SPOT phase only)
       * @example 0
       */
      guessX?: number;
      /**
       * Format: double
       * @description Guessed Y coordinate (SPOT phase only)
       * @example 0
       */
      guessY?: number;
      /**
       * Format: double
       * @description Guessed Z coordinate (SPOT phase only)
       * @example 0
       */
      guessZ?: number;
    };
    /** @description Current round information (spawn coordinates withheld) */
    RoundResponse: {
      /**
       * Format: int32
       * @description 1-based round number
       * @example 1
       */
      roundNumber?: number;
      /**
       * @description Game identifier
       * @example mario-kart-8
       */
      gameId?: string;
      /**
       * @description Level / track identifier (displayed to player)
       * @example TBD-1
       */
      levelId?: string;
      /**
       * @description Current phase of this round
       * @example GAME
       * @enum {string}
       */
      currentPhase?: 'GAME' | 'LEVEL' | 'SPOT';
      /** @description Whether this round has been completed */
      finished?: boolean;
      /**
       * Format: int64
       * @description Epoch milliseconds when this round started
       */
      startedAt?: number;
    };
    /** @description Final match results including true spawn coordinates per round */
    ResultsResponse: {
      /**
       * @description Room code
       * @example ABC123
       */
      roomCode?: string;
      /**
       * @description Final status of the match
       * @example FINISHED
       */
      matchStatus?: string;
      rounds?: components['schemas']['RoundResult'][];
    };
    /** @description Per-round result revealing the true location */
    RoundResult: {
      /** Format: int32 */
      roundNumber?: number;
      gameId?: string;
      levelId?: string;
      /**
       * Format: double
       * @description True spawn X coordinate
       */
      trueSpawnX?: number;
      /**
       * Format: double
       * @description True spawn Y coordinate
       */
      trueSpawnY?: number;
      /**
       * Format: double
       * @description True spawn Z coordinate
       */
      trueSpawnZ?: number;
      finished?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  startMatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Room code
         * @example ABC123
         */
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartMatchRequest'];
      };
    };
    responses: {
      /** @description Match started */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Room not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Match already started */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  submitGuess: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Room code
         * @example ABC123
         */
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GuessRequest'];
      };
    };
    responses: {
      /** @description Guess accepted and published */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid phase or missing fields */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Room or match not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCurrentRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Room code
         * @example ABC123
         */
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Round info returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RoundResponse'];
        };
      };
      /** @description Room or match not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RoundResponse'];
        };
      };
    };
  };
  getResults: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Room code
         * @example ABC123
         */
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Results returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ResultsResponse'];
        };
      };
      /** @description Room or match not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ResultsResponse'];
        };
      };
    };
  };
}
