/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/leaderboard/room/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get room leaderboard
         * @description Returns the current ranking within a specific room.
         */
        get: operations["getRoomLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get global leaderboard
         * @description Returns top players across all games.
         */
        get: operations["getGlobalLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EntryResponse: {
            /** Format: int64 */
            rank?: number;
            playerId?: string;
            /** Format: double */
            score?: number;
        };
        LeaderboardResponse: {
            leaderboardType?: string;
            identifier?: string;
            entries?: components["schemas"]["EntryResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRoomLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Room code
                 * @example ABC123
                 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room leaderboard returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeaderboardResponse"];
                };
            };
        };
    };
    getGlobalLeaderboard: {
        parameters: {
            query?: {
                /**
                 * @description Number of top entries to return
                 * @example 100
                 */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeaderboardResponse"];
                };
            };
        };
    };
}
