/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List open rooms
         * @description Returns all rooms with OPEN status.
         */
        get: operations["listOpenRooms"];
        put?: never;
        /**
         * Create a room
         * @description Creates a new room and publishes a game.room.events Kafka event.
         */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a room
         * @description Adds a player to the lobby.
         */
        post: operations["joinRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{code}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update room settings
         * @description Updates round count, time limit, or game pack. Host-only.
         */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api/v1/rooms/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get room details
         * @description Returns room details including players, settings, and status.
         */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{code}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave a room
         * @description Removes yourself from the lobby. If the host leaves, the room is closed.
         */
        delete: operations["leaveRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request to create a new room */
        CreateRoomRequest: {
            /**
             * @description ID of the host player creating the room
             * @example user-uuid-123
             */
            hostId: string;
            /**
             * @description Whether the room is private (invite-only)
             * @example false
             */
            isPrivate?: boolean;
        };
        PlayerResponse: {
            playerId?: string;
            displayName?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        RoomResponse: {
            roomCode?: string;
            hostId?: string;
            status?: string;
            /** Format: int32 */
            maxPlayers?: number;
            settings?: components["schemas"]["SettingsResponse"];
            players?: components["schemas"]["PlayerResponse"][];
            /** Format: date-time */
            createdAt?: string;
            private?: boolean;
        };
        SettingsResponse: {
            /** Format: int32 */
            roundCount?: number;
            /** Format: int32 */
            timeLimitSeconds?: number;
            gamePack?: string;
        };
        /** @description Request to join a room */
        JoinRoomRequest: {
            /**
             * @description ID of the player joining
             * @example user-uuid-456
             */
            playerId: string;
            /**
             * @description Display name of the player
             * @example Player1
             */
            displayName: string;
        };
        /** @description Request to update room settings (host-only) */
        UpdateSettingsRequest: {
            /**
             * @description ID of the player requesting changes (must be host)
             * @example user-uuid-123
             */
            playerId: string;
            /**
             * Format: int32
             * @description Number of rounds per match
             * @example 5
             */
            roundCount?: number;
            /**
             * Format: int32
             * @description Time limit per round in seconds
             * @example 60
             */
            timeLimitSeconds?: number;
            /**
             * @description Game pack identifier
             * @example mario-kart
             */
            gamePack?: string;
        };
        /** @description Request to leave a room */
        LeaveRoomRequest: {
            /**
             * @description ID of the player leaving
             * @example user-uuid-456
             */
            playerId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOpenRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"][];
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Room created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    joinRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Room code
                 * @example ABC123
                 */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRoomRequest"];
            };
        };
        responses: {
            /** @description Player joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Room full or player already in room */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Room code
                 * @example ABC123
                 */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Not the host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Room code
                 * @example ABC123
                 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room details returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    leaveRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Room code
                 * @example ABC123
                 */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRoomRequest"];
            };
        };
        responses: {
            /** @description Player left */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
