/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/scoring/{roomCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get match scores
         * @description Returns all scores for an entire match.
         */
        get: operations["getMatchScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scoring/{roomCode}/rounds/{roundNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get round scores
         * @description Returns all scores for a specific round.
         */
        get: operations["getRoundScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ScoreItem: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            roundNumber?: number;
            playerId?: string;
            phase?: string;
            /** Format: int32 */
            points?: number;
            correct?: boolean;
            /** Format: int64 */
            timeBonusMs?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ScoresResponse: {
            roomCode?: string;
            scores?: components["schemas"]["ScoreItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMatchScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room code */
                roomCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scores returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScoresResponse"];
                };
            };
        };
    };
    getRoundScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room code */
                roomCode: string;
                /** @description Round number */
                roundNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scores returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScoresResponse"];
                };
            };
        };
    };
}
