// This file is auto-generated by @hey-api/openapi-ts

export { getGlobalLeaderboard, getRoomLeaderboard, type Options } from './sdk.gen';
export type {
  ClientOptions,
  EntryResponse,
  GetGlobalLeaderboardData,
  GetGlobalLeaderboardResponse,
  GetGlobalLeaderboardResponses,
  GetRoomLeaderboardData,
  GetRoomLeaderboardResponse,
  GetRoomLeaderboardResponses,
  LeaderboardResponse,
} from './types.gen';
