// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetGlobalLeaderboardData,
  GetGlobalLeaderboardResponses,
  GetRoomLeaderboardData,
  GetRoomLeaderboardResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get room leaderboard
 *
 * Returns the current ranking within a specific room.
 */
export const getRoomLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<GetRoomLeaderboardData, ThrowOnError>
) =>
  (options.client ?? client).get<GetRoomLeaderboardResponses, unknown, ThrowOnError>({
    url: '/api/v1/leaderboard/room/{code}',
    ...options,
  });

/**
 * Get global leaderboard
 *
 * Returns top players across all games.
 */
export const getGlobalLeaderboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetGlobalLeaderboardData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetGlobalLeaderboardResponses, unknown, ThrowOnError>({
    url: '/api/v1/leaderboard/global',
    ...options,
  });
