// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8085' | (string & {});
};

/**
 * A single leaderboard entry
 */
export type EntryResponse = {
  /**
   * Player's rank (1 = highest)
   */
  rank?: number;
  /**
   * Player's user ID
   */
  playerId?: string;
  /**
   * Player's total score
   */
  score?: number;
};

/**
 * Ranked leaderboard entries for a room or globally
 */
export type LeaderboardResponse = {
  /**
   * Type of leaderboard
   */
  leaderboardType?: 'room' | 'global';
  /**
   * Room code for room leaderboard, or 'all' for global
   */
  identifier?: string;
  /**
   * Ranked list of players and their scores
   */
  entries?: Array<EntryResponse>;
};

export type GetRoomLeaderboardData = {
  body?: never;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/leaderboard/room/{code}';
};

export type GetRoomLeaderboardResponses = {
  /**
   * Room leaderboard returned
   */
  200: LeaderboardResponse;
};

export type GetRoomLeaderboardResponse =
  GetRoomLeaderboardResponses[keyof GetRoomLeaderboardResponses];

export type GetGlobalLeaderboardData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Number of top entries to return
     */
    top?: number;
  };
  url: '/api/v1/leaderboard/global';
};

export type GetGlobalLeaderboardResponses = {
  /**
   * Leaderboard returned
   */
  200: LeaderboardResponse;
};

export type GetGlobalLeaderboardResponse =
  GetGlobalLeaderboardResponses[keyof GetGlobalLeaderboardResponses];
