// This file is auto-generated by @hey-api/openapi-ts

export { getCurrentRound, getResults, type Options, startMatch, submitGuess } from './sdk.gen';
export type {
  ClientOptions,
  GetCurrentRoundData,
  GetCurrentRoundError,
  GetCurrentRoundErrors,
  GetCurrentRoundResponse,
  GetCurrentRoundResponses,
  GetResultsData,
  GetResultsError,
  GetResultsErrors,
  GetResultsResponse,
  GetResultsResponses,
  GuessRequest,
  ResultsResponse,
  RoundResponse,
  RoundResult,
  StartMatchData,
  StartMatchErrors,
  StartMatchRequest,
  StartMatchResponses,
  SubmitGuessData,
  SubmitGuessErrors,
  SubmitGuessResponses,
} from './types.gen';
