// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetCurrentRoundData,
  GetCurrentRoundErrors,
  GetCurrentRoundResponses,
  GetResultsData,
  GetResultsErrors,
  GetResultsResponses,
  StartMatchData,
  StartMatchErrors,
  StartMatchResponses,
  SubmitGuessData,
  SubmitGuessErrors,
  SubmitGuessResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Start a match
 */
export const startMatch = <ThrowOnError extends boolean = false>(
  options: Options<StartMatchData, ThrowOnError>
) =>
  (options.client ?? client).post<StartMatchResponses, StartMatchErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Submit a guess
 */
export const submitGuess = <ThrowOnError extends boolean = false>(
  options: Options<SubmitGuessData, ThrowOnError>
) =>
  (options.client ?? client).post<SubmitGuessResponses, SubmitGuessErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/guess',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get current round
 */
export const getCurrentRound = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrentRoundData, ThrowOnError>
) =>
  (options.client ?? client).get<GetCurrentRoundResponses, GetCurrentRoundErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/round',
    ...options,
  });

/**
 * Get match results
 */
export const getResults = <ThrowOnError extends boolean = false>(
  options: Options<GetResultsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetResultsResponses, GetResultsErrors, ThrowOnError>({
    url: '/api/v1/rooms/{code}/results',
    ...options,
  });
