// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8082' | 'http://game-service:8082' | (string & {});
};

/**
 * Request to start a match for a given room
 */
export type StartMatchRequest = {
  /**
   * ID of the host player initiating the match
   */
  hostId: string;
  /**
   * IDs of all players in the room
   */
  playerIds: Array<string>;
};

/**
 * A player's guess for the current round phase
 */
export type GuessRequest = {
  /**
   * Player's user ID
   */
  playerId: string;
  /**
   * Which phase this guess targets
   */
  phase: 'GAME' | 'LEVEL' | 'SPOT';
  /**
   * Text answer for GAME or LEVEL phase
   */
  textAnswer?: string;
  /**
   * Guessed X coordinate (SPOT phase only)
   */
  guessX?: number;
  /**
   * Guessed Y coordinate (SPOT phase only)
   */
  guessY?: number;
  /**
   * Guessed Z coordinate (SPOT phase only)
   */
  guessZ?: number;
};

/**
 * Current round information (spawn coordinates withheld)
 */
export type RoundResponse = {
  /**
   * 1-based round number
   */
  roundNumber?: number;
  /**
   * Game identifier
   */
  gameId?: string;
  /**
   * Level / track identifier (displayed to player)
   */
  levelId?: string;
  /**
   * Current phase of this round
   */
  currentPhase?: 'GAME' | 'LEVEL' | 'SPOT';
  /**
   * Noclip hash for the 3D viewer
   */
  noclipHash?: string;
  /**
   * Whether this round has been completed
   */
  finished?: boolean;
  /**
   * Epoch milliseconds when this round started
   */
  startedAt?: number;
};

/**
 * Final match results including true spawn coordinates per round
 */
export type ResultsResponse = {
  /**
   * Room code
   */
  roomCode?: string;
  /**
   * Final status of the match
   */
  matchStatus?: string;
  rounds?: Array<RoundResult>;
};

/**
 * Per-round result revealing the true location
 */
export type RoundResult = {
  roundNumber?: number;
  gameId?: string;
  levelId?: string;
  noclipHash?: string;
  /**
   * True spawn X coordinate
   */
  trueSpawnX?: number;
  /**
   * True spawn Z coordinate
   */
  trueSpawnZ?: number;
  finished?: boolean;
};

export type StartMatchData = {
  body: StartMatchRequest;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/start';
};

export type StartMatchErrors = {
  /**
   * Room not found
   */
  404: unknown;
  /**
   * Match already started
   */
  409: unknown;
};

export type StartMatchResponses = {
  /**
   * Match started
   */
  201: unknown;
};

export type SubmitGuessData = {
  body: GuessRequest;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/guess';
};

export type SubmitGuessErrors = {
  /**
   * Invalid phase or missing fields
   */
  400: unknown;
  /**
   * Room or match not found
   */
  404: unknown;
};

export type SubmitGuessResponses = {
  /**
   * Guess accepted and published
   */
  202: unknown;
};

export type GetCurrentRoundData = {
  body?: never;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/round';
};

export type GetCurrentRoundErrors = {
  /**
   * Room or match not found
   */
  404: RoundResponse;
};

export type GetCurrentRoundError = GetCurrentRoundErrors[keyof GetCurrentRoundErrors];

export type GetCurrentRoundResponses = {
  /**
   * Round info returned
   */
  200: RoundResponse;
};

export type GetCurrentRoundResponse = GetCurrentRoundResponses[keyof GetCurrentRoundResponses];

export type GetResultsData = {
  body?: never;
  path: {
    /**
     * Room code
     */
    code: string;
  };
  query?: never;
  url: '/api/v1/rooms/{code}/results';
};

export type GetResultsErrors = {
  /**
   * Room or match not found
   */
  404: ResultsResponse;
};

export type GetResultsError = GetResultsErrors[keyof GetResultsErrors];

export type GetResultsResponses = {
  /**
   * Results returned
   */
  200: ResultsResponse;
};

export type GetResultsResponse = GetResultsResponses[keyof GetResultsResponses];
