// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8081' | 'http://auth-service:8081' | (string & {});
};

export type RegisterRequest = {
  username: string;
  password: string;
};

export type AuthResponse = {
  id?: string;
  username?: string;
  token?: string;
};

export type LoginRequest = {
  username: string;
  password: string;
};

export type RegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/api/auth/register';
};

export type RegisterErrors = {
  /**
   * Invalid request or username already exists
   */
  400: AuthResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
  /**
   * User registered successfully
   */
  201: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
  body?: never;
  headers?: {
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutErrors = {
  /**
   * Missing or invalid authorization header
   */
  401: unknown;
};

export type LogoutResponses = {
  /**
   * Logout successful
   */
  204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type LoginErrors = {
  /**
   * Invalid credentials
   */
  401: AuthResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Authentication successful
   */
  200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];
