// This file is auto-generated by @hey-api/openapi-ts

import type { DefaultError, UseMutationOptions } from '@tanstack/react-query';

import { login, logout, type Options, register } from '../sdk.gen';
import type {
  LoginData,
  LoginError,
  LoginResponse,
  LogoutData,
  LogoutResponse,
  RegisterData,
  RegisterError,
  RegisterResponse,
} from '../types.gen';

/**
 * Register a new user
 */
export const registerMutation = (
  options?: Partial<Options<RegisterData>>
): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
  const mutationOptions: UseMutationOptions<
    RegisterResponse,
    RegisterError,
    Options<RegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await register({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout and invalidate JWT token
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>
): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Authenticate user and get JWT token
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
  const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await login({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
