kraft:
  enabled: true

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

broker:
  replicaCount: 0

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT

persistence:
  enabled: true
  size: 2Gi
